// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egaroeikmbyevdichpsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnYXJvZWlrbWJ5ZXZkaWNocHNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NDU3NzYsImV4cCI6MjA1ODEyMTc3Nn0.DuBRkZ9yZj5pcRIY5IyVJklz7ocRQluL6-uCN7UWwOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);